run:
  timeout: 10m
  modules-download-mode: readonly

linters:
  enable-all: false
  enable:
    - dupl
    - errcheck
    - goconst
    - gocritic
    - gofmt
    - gosimple
    - govet
    - ineffassign
    - misspell
    - staticcheck
    - typecheck
    - unconvert
    - unused
    - revive

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  exclude-rules:
    - path: '(.+)_test\.go'
      linters:
        - dupl
        - errcheck

