name: Go

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.22.6"
      - name: Build
        run: make build
  lint:
    runs-on: ubuntu-latest
    container:
      image: golangci/golangci-lint:v1.59.1
      options: --user 1001
    steps:
      - uses: actions/checkout@v3
      - name: Lint
        run: golangci-lint -c .golangci.yml run
